server:
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true

tims: {}


com:
  essaid:
    hapi-ext:
      restful-server:
        configurers:
          enabled: true
          type: map # map to use the mapping configuration, or 'context' (the default) to look up all implementations in the context
          map:
            timesServerConfigurer: class:com.github.hotecosystem.hapi.server.TimsRestfulServerConfigurer
      index:
        analysis:
          apply-defaults: true
          configurers:
            enabled: true
            type: map # map to use the mapping configuration, or 'context' (the default) to look up all implementations in the context
            map: {}
        mapping:
          configurers:
            enabled: true
            type: map # map to use the mapping configuration, or 'context' (the default) to look up all implementations in the context
            map:
              timsIndexMappingConfigurer: class:com.github.hotecosystem.hapi.index.TimsMappingConfigurer
      entity-manager-factory:
        process-properties: true
        default-properties: {}
        override-properties:
          "hibernate.search.backend.analysis.configurer": class:com.essaid.fhir.hapi.ext.HapiExtensionConfiguration
          "hibernate.search.mapping.configurer": class:com.essaid.fhir.hapi.ext.HapiExtensionConfiguration